/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Jair
 */
public class InformationAirship extends javax.swing.JPanel {

    /**
     * Creates new form InformationAirship
     */
    public InformationAirship() {
        initComponents();
        
        Font estilo = new Font(aeronave.getFont().getName(), aeronave.getFont().getStyle(), 12);
        
        mgrsLabel.setFont(estilo);
        altitudLabel.setFont(estilo);
        alturaLabel.setFont(estilo);
        velocidadLabel.setFont(estilo);
        longitudLabel.setFont(estilo);
        latitudLabel.setFont(estilo);
        jLabel1.setFont(estilo);
        
        aeronave.setText("Aeronave No. X");
        aeronave.setHorizontalAlignment(SwingConstants.CENTER);
        aeronave.setFont(new Font(aeronave.getFont().getName(), aeronave.getFont().getStyle(), 18));
        aeronave.setMaximumSize(new Dimension(600, 25));
        aeronave.setBackground(new Color(0, 134, 191, 255));
        aeronave.setForeground(Color.WHITE);
        aeronave.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        aeronave = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        latitudLabel = new javax.swing.JLabel();
        longitudLabel = new javax.swing.JLabel();
        mgrsLabel = new javax.swing.JLabel();
        altitudLabel = new javax.swing.JLabel();
        alturaLabel = new javax.swing.JLabel();
        velocidadLabel = new javax.swing.JLabel();
        elevacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(51, 51, 51));

        aeronave.setText("jTextField1");

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        latitudLabel.setBackground(new java.awt.Color(102, 102, 102));
        latitudLabel.setForeground(new java.awt.Color(255, 255, 255));
        latitudLabel.setText("Latitud: NaN");
        jPanel1.add(latitudLabel);

        longitudLabel.setBackground(new java.awt.Color(102, 102, 102));
        longitudLabel.setForeground(new java.awt.Color(255, 255, 255));
        longitudLabel.setText("Longitud: NaN");
        jPanel1.add(longitudLabel);

        mgrsLabel.setBackground(new java.awt.Color(102, 102, 102));
        mgrsLabel.setForeground(new java.awt.Color(255, 255, 255));
        mgrsLabel.setText("MGRS: NaN                         ");
        jPanel1.add(mgrsLabel);

        altitudLabel.setBackground(new java.awt.Color(102, 102, 102));
        altitudLabel.setForeground(new java.awt.Color(255, 255, 255));
        altitudLabel.setText("Altitud: NaN");
        jPanel1.add(altitudLabel);

        alturaLabel.setForeground(new java.awt.Color(255, 255, 255));
        alturaLabel.setText("Altura: NaN");
        jPanel1.add(alturaLabel);

        velocidadLabel.setForeground(new java.awt.Color(255, 255, 255));
        velocidadLabel.setText("Velocidad: NaN");
        jPanel1.add(velocidadLabel);

        jPanel4.add(jPanel1);

        elevacion.setBackground(new java.awt.Color(0, 0, 0));
        elevacion.setForeground(new java.awt.Color(255, 255, 255));
        elevacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes/grafica.png"))); // NOI18N
        jPanel4.add(elevacion);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NaN");
        jPanel4.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aeronave)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getAeronave() {
        return aeronave;
    }
    
    public void setNombreAeronave(String string){
        
    }    

    public JLabel getAltitudLabel() {
        return altitudLabel;
    }
    
    public void setAltitudLabel(String string){
        latitudLabel.setText(string);
    }

    public JLabel getAlturaLabel() {
        return alturaLabel;
    }

    public void setAlturaLabel(String string){
        altitudLabel.setText(string);
    }
    
    public JLabel getElevacion() {
        return jLabel1;
    }
    
    public void setElevationLabel(String string){
        elevacion.setText(string);
    }

    public JLabel getLatitudLabel() {
        return latitudLabel;
    }
    
    public void setLatitudLabel(String string){
        latitudLabel.setText(string);
    }

    public JLabel getLongitudLabel() {
        return longitudLabel;
    }
    
    public void setLongitudLabel(String string){
        longitudLabel.setText(string);
    }

    public JLabel getMgrsLabel() {
        return mgrsLabel;
    }

    public void setMgrsLabel(String string){
        mgrsLabel.setText(string);
    }
    
    public JLabel getVelocidadLabel() {
        return velocidadLabel;
    }
    
    public void setVelocidadLabel(String string){
        velocidadLabel.setText(string);
    }

    public void setTextTextField(String string){
        aeronave.setText("Aeronave: "+string);
    }  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aeronave;
    private javax.swing.JLabel altitudLabel;
    private javax.swing.JLabel alturaLabel;
    private javax.swing.JLabel elevacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel latitudLabel;
    private javax.swing.JLabel longitudLabel;
    private javax.swing.JLabel mgrsLabel;
    private javax.swing.JLabel velocidadLabel;
    // End of variables declaration//GEN-END:variables

    

}
